#!/usr/bin/env python3
"""Emit tools/playtest/symbols.lua from the built ELF.

Run after every `make` (run.sh does this) -- BSS/EWRAM addresses shift when
engine code changes, so the Lua harness must never hard-code them.
"""
import os
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ELF = os.path.join(REPO, 'fireemblem8u', 'fireemblem8.elf')
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'symbols.lua')

# Symbols the harness reads/scans. Struct offsets live in harness.lua next to
# the decomp header they came from.
WANTED = [
    'gPlaySt',                  # chapter index / phase / turn (include/types.h)
    'gBmSt',                    # live map cursor (include/types.h)
    'gUnitArrayBlue',           # player units (include/bmunit.h)
    'gUnitArrayRed',            # enemy units
    'sProcArray',               # proc pool: 64 x 0x6C (src/proc.c)
    'gBmMapMovement',           # u8** move-cost map, valid while a unit is selected
                                # (include/bmmap.h; < 120 = reachable)
    'gChapterFlagBits',         # event flags < 100, bit (flag-1) (src/eventinfo.c)
    'gPermanentFlagBits',       # event flags > 100, bit (flag-101)
    'ProcScr_GameOverScreen',   # proc script: game-over screen active
    'sProc_Menu',               # proc script: a menu is open
    'gProcScr_ChapterStatusScreen',  # proc script: map-menu Status screen, which
                                # draws the chapter title card (src/uichapterstatus.c)
]


def main():
    if not os.path.exists(ELF):
        sys.exit('ERROR: %s not built (run make first)' % ELF)
    nm = subprocess.run(['arm-none-eabi-nm', ELF], capture_output=True, text=True, check=True)
    addrs = {}
    for line in nm.stdout.splitlines():
        parts = line.split()
        if len(parts) == 3 and parts[2] in WANTED:
            addrs[parts[2]] = int(parts[0], 16)
    missing = [w for w in WANTED if w not in addrs]
    if missing:
        sys.exit('ERROR: symbols not found in ELF: %s' % ', '.join(missing))
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('-- generated by gen_symbols.py from fireemblem8.elf; do not edit\n')
        f.write('SYM = {\n')
        for name in WANTED:
            f.write('    %s = 0x%08X,\n' % (name, addrs[name]))
        f.write('}\n')
    print('wrote %s (%d symbols)' % (OUT, len(addrs)))


if __name__ == '__main__':
    main()
