#!/usr/bin/env python3
"""Emit tools/playtest/symbols.lua from the built ELF.

Run after every `make` (run.sh does this) -- BSS/EWRAM addresses shift when
engine code changes, so the Lua harness must never hard-code them.
"""
import os
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ELF = os.path.join(REPO, 'fireemblem8u', 'fireemblem8.elf')
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'symbols.lua')

# Symbols the harness reads/scans. Struct offsets live in harness.lua next to
# the decomp header they came from.
WANTED = [
    'gPlaySt',                  # chapter index / phase / turn (include/types.h)
    'gBmSt',                    # live map cursor (include/types.h)
    'gUnitArrayBlue',           # player units (include/bmunit.h)
    'gUnitArrayRed',            # enemy units
    'gUnitArrayGreen',          # green (ally/NPC) units (include/bmunit.h) -- the ch02 chwinga
                                # protect layer rides this array (FACTION_ID_GREEN).
    'gConvoyItemArray',         # the convoy (extern u16[]; include/variables.h). Low byte of
                                # each entry is the item id -- where an overflow charm-gift lands.
    'gConvoyItemCount',         # u8 count of live convoy entries (include/bmcontainer.h).
    'gItemData',                # struct ItemData[] (include/bmitem.h): per-item attributes
                                # (IA_WEAPON/IA_STAFF @ +0x08) + encodedRange (min<<4|max @ +0x19).
                                # Lets the harness read a unit's weapon reach generically.
    'sProcArray',               # proc pool: 64 x 0x6C (src/proc.c)
    'gBmMapMovement',           # u8** move-cost map, valid while a unit is selected
                                # (include/bmmap.h; < 120 = reachable)
    'gBmMapUnit',               # u8** tile->unit grid (include/bmmap.h): gBmMapUnit[y][x] is the
                                # on-tile unit id the engine uses for cursor selection. Relocating
                                # a unit must update THIS, not just its xPos/yPos.
    'gChapterFlagBits',         # event flags < 100, bit (flag-1) (src/eventinfo.c)
    'gPermanentFlagBits',       # event flags > 100, bit (flag-101)
    'ProcScr_GameOverScreen',   # proc script: game-over screen active
    'sProc_Menu',               # proc script: a menu is open
    'gProcScr_ChapterStatusScreen',  # proc script: map-menu Status screen, which
                                # draws the chapter title card (src/uichapterstatus.c)
    'gProcScr_SALLYCURSOR',     # proc script: the preparations screen
                                # (src/prep_sallycursor.c; opened by event cmd 0x3E)
    'gProcScr_TitleScreen',     # proc script: the title screen (src/titlescreen.c).
                                # Active after the dev placeholder's MNTS return.
    'gProcScr_OpSubtitle',      # proc script: the opening subtitle crawl (src/opsubtitle.c).
                                # In a --montage build this carries the #43 lore crawl, so a
                                # live instance == the montage opener actually played.
    'ProcScr_PrepUnitScreen',   # proc script: the prep "Pick Units" screen (deploy/bench).
    'ProcScr_BmSupplyScreen',   # proc script: the in-map Supply (convoy) screen, opened by
                                # the unit-menu Supply command (src/prep_itemsupply.c). A live
                                # instance == a unit actually opened the convoy on the field.
    'ProcScr_BattleEventEngine',# proc script: in-battle event engine (src/event.c). Runs
                                # CallBattleQuoteEventInBattle -> the brief in-combat quotes
                                # (per-PC DEATH quotes, boss taunts). A live instance == a
                                # quote box is on screen NOW -> hold + screenshot it.
    'ProcScr_StdEventEngine',   # proc script: the standard (map) event engine. A live
                                # instance == a map cutscene/talk event is running.
    'gProc_ekrBattle',          # proc script: the on-map battle (EKR) animation engine
                                # (src/banim-ekrbattle.c). A live instance == a combat is
                                # actually animating -> used to confirm an attack committed.
]


def main():
    if not os.path.exists(ELF):
        sys.exit('ERROR: %s not built (run make first)' % ELF)
    nm = subprocess.run(['arm-none-eabi-nm', ELF], capture_output=True, text=True, check=True)
    addrs = {}
    for line in nm.stdout.splitlines():
        parts = line.split()
        if len(parts) == 3 and parts[2] in WANTED:
            addrs[parts[2]] = int(parts[0], 16)
    missing = [w for w in WANTED if w not in addrs]
    if missing:
        sys.exit('ERROR: symbols not found in ELF: %s' % ', '.join(missing))
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('-- generated by gen_symbols.py from fireemblem8.elf; do not edit\n')
        f.write('SYM = {\n')
        for name in WANTED:
            f.write('    %s = 0x%08X,\n' % (name, addrs[name]))
        f.write('}\n')
    print('wrote %s (%d symbols)' % (OUT, len(addrs)))


if __name__ == '__main__':
    main()
